updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "e2e"
      - "server"
      - "web"
    schedule:
      interval: "weekly"
    groups:
      npm:
        applies-to: "version-updates"
        update-types:
          - "minor"
  - package-ecosystem: "docker"
    directories:
      - "server"
      - "web"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
