changelog:
  exclude:
    labels:
      - "exclude from release notes"
  categories:
    - title: "Breaking Changes"
      labels:
        - "breaking change"
    - title: "Deprecated"
      labels:
        - "deprecated"
    - title: "Features"
      labels:
        - "feature"
        - "new feature" # old label
    - title: "Improvements"
      labels:
        - "improvement"
    - title: "Fixes"
      labels:
        - "bug fix"
        - "bug" # old label
    - title: "Chore"
      labels:
        - "chore"
        - "maintenance" # old label
    - title: "Dependencies"
      labels:
        - "dependencies"
    - title: "Github Actions"
      labels:
        - "github actions"
    - title: "Other"
      labels:
        - "*"
