# Bootstraps the local development environment.
services:
  web:
    extends:
      file: compose.base.yaml
      service: web-base
    container_name: keijo-web
    environment:
      - VITE_API_URL=http://localhost:3001/graphql
    ports:
      - 3000:5173

  web-test:
    extends:
      file: compose.base.yaml
      service: web-base
    container_name: keijo-web-test
    environment:
      - VITE_API_URL=http://localhost:4001/graphql
    ports:
      - 4000:5173

  server:
    extends:
      file: compose.base.yaml
      service: server-base
    container_name: keijo-server
    ports:
      - 3001:3001

  server-test:
    extends:
      file: compose.base.yaml
      service: server-base
    container_name: keijo-server-test
    environment:
      - NETVISOR_API_URL=http://nv-mock:4002
    ports:
      - 4001:3001

  nv-mock:
    extends:
      file: compose.services.yaml
      service: nv-mock

  db:
    extends:
      file: compose.services.yaml
      service: db

volumes:
  keijo-pg:
