# Bootstraps the local development environment. Not for production use.
services:
  web:
    build: ./web/
    container_name: keijo-web
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://localhost:3001/graphql
    ports:
      - 3000:5173
    volumes:
      - ./web/src:/usr/src/app/src
      - ./web/public:/usr/src/app/public

  server:
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
      target: dev
    container_name: keijo-server
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3001
    ports:
      - 3001:3001
    volumes:
      - ./server/src:/usr/src/app/src

  nv-mock:
    image: mockoon/cli
    container_name: nv-mock
    ports:
      - 4002:4002
    volumes:
      - ./nv-mock:/data
    command: "--port 4002 --data /data/nv-mock.json"
