# Bootstraps the local development environment.
name: keijo-local

services:
  web:
    extends:
      file: compose.base.yaml
      service: web-base
    container_name: keijo-web
    environment:
      - VITE_API_URL=http://localhost:3001/graphql
      - VITE_KEIJO_JIRA_API_URL=http://localhost:3001/jira
    ports:
      - 3000:5173

  web-test:
    extends:
      file: compose.base.yaml
      service: web-base
    container_name: keijo-web-test
    environment:
      - VITE_API_URL=http://localhost:4001/graphql
      - VITE_KEIJO_JIRA_API_URL=http://localhost:4001/jira
    ports:
      - 4000:5173

  server:
    extends:
      file: compose.base.yaml
      service: server-base
    container_name: keijo-server
    environment:
      CORS_ORIGIN: http://localhost:3000
      CALLBACK_URL: http://localhost:3001/jira/callback
      CALLBACK_REDIRECT_URL: http://localhost:3000
      DATABASE_NAME: keijo_dev
    ports:
      - 3001:3001

  server-test:
    extends:
      file: compose.base.yaml
      service: server-base
    container_name: keijo-server-test
    environment:
      NETVISOR_API_URL: http://nv-mock:4002
      DATABASE_NAME: keijo_test
      CORS_ORIGIN: http://localhost:4000
    ports:
      - 4001:3001

  nv-mock:
    extends:
      file: compose.services.yaml
      service: nv-mock

  db:
    extends:
      file: compose.services.yaml
      service: db
    volumes:
      - type: volume
        source: keijo-pg
        target: /var/lib/postgresql/data

volumes:
  keijo-pg:
