import "@fontsource/roboto";
import { CssBaseline } from "@mui/material";
import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <CssBaseline />
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
