name: Build and save image

on:
  workflow_call:

jobs:
  build-test:
    name: Build and save test image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # This image includes dev dependencies for running tests etc.
      - name: Build test image
        uses: docker/build-push-action@v4
        with:
          context: server
          file: server/Dockerfile.dev
          tags: keijo-test
          outputs: type=docker,dest=/tmp/keijo-test.tar
      - name: Save test image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: keijo-test
          path: /tmp/keijo-test.tar
      # This is the production image for E2E testing and release.
      - name: Build production image
        uses: docker/build-push-action@v4
        with:
          context: server
          tags: keijo
          outputs: type=docker,dest=/tmp/keijo.tar
      - name: Save production image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: keijo
          path: /tmp/keijo.tar
