name: Build and save images

on:
  workflow_call:

jobs:
  build:
    name: Build and save images
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # This image includes dev dependencies for running tests etc.
      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          context: server
          file: server/Dockerfile.dev
          tags: keijo-test
          outputs: type=docker,dest=/tmp/keijo-test.tar
          secrets: |
            "mui_x_license=${{ secrets.MUI_X_LICENSE }}"
      - name: Save test image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: keijo-test
          path: /tmp/keijo-test.tar
          retention-days: 1
      # This is the production image for E2E testing and release.
      - name: Build production image
        uses: docker/build-push-action@v6
        with:
          file: server/Dockerfile
          tags: keijo
          outputs: type=docker,dest=/tmp/keijo.tar
          secrets: |
            "mui_x_license=${{ secrets.MUI_X_LICENSE }}"
      - name: Save production image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: keijo
          path: /tmp/keijo.tar
          retention-days: 1
