name: Push (main)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build image
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit

  tests:
    name: Run tests
    uses: ./.github/workflows/run_tests.yaml
    needs:
      - build

  publish:
    name: Publish image (next)
    runs-on: ubuntu-24.04
    needs:
      - build
      - tests
    permissions:
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: keijo
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/keijo.tar
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag image
        run: docker tag keijo ghcr.io/funidata/keijo:next
      - name: Push image to GHCR
        run: docker push ghcr.io/funidata/keijo:next
