name: Release new version

on:
  release:
    types:
      - released

jobs:
  build:
    name: Build image
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit

  tests:
    name: Run tests
    uses: ./.github/workflows/run_tests.yaml
    needs:
      - build

  publish:
    name: Publish image
    runs-on: ubuntu-latest
    needs:
      - build
      - tests
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Parse semver number from package.json
        id: semver
        run: |
          PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')
          echo "::set-output name=major::$(echo $PACKAGE_VERSION | cut -d "." -f 1)"
          echo "::set-output name=minor::$(echo $PACKAGE_VERSION | cut -d "." -f 2)"
          echo "::set-output name=patch::$(echo $PACKAGE_VERSION | cut -d "." -f 3)"
      - name: Compose semver tags
        id: tags
        run: |
          echo "::set-output name=major::${{ steps.semver.outputs.major }}"
          echo "::set-output name=minor::${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}"
          echo "::set-output name=full::${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.${{ steps.semver.outputs.patch }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: keijo
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/keijo.tar
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag image
        run: |
          docker tag keijo ghcr.io/funidata/keijo:${{ steps.tags.outputs.full }}
          docker tag keijo ghcr.io/funidata/keijo:${{ steps.tags.outputs.minor }}
          docker tag keijo ghcr.io/funidata/keijo:${{ steps.tags.outputs.major }}
          docker tag keijo ghcr.io/funidata/keijo:latest
      - name: Push image to GHCR
        run: docker push --all-tags ghcr.io/funidata/keijo
